config/routes.rb
Rails.application.routes.draw do
  root                   'static_pages#home'

  get     'help'      => 'static_pages#help'
  get     'about'     => 'static_pages#about'
  get     'contact'   => 'static_pages#contact'

  get     'signup'    => 'users#new'

  get     'login'     => 'sessions#new'
  post    'login'     => 'sessions#create'
  delete  'logout'    => 'sessions#destroy'

  get     'todolists' => 'todo_lists#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
        patch :uncomplete
        post 'priority_up'
        post 'priority_down'
      end
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  # belongs_to :user
  belongs_to :todo_list
  validates :content, presence: true
  validates :todo_list_id, presence: true

  def completed?
    !completed_at.blank?
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  # def new
	# 	@item = current_user.items.build
  # end
  # def show
  # end

  def create
    # @todo_item = @todo_list.todo_items.create(todo_item_params)
    if current_user.todo_lists.find(set_todo_list.id).todo_items.count>0
	    priority = current_user.todo_lists.find(set_todo_list.id).todo_items.maximum(:priority)+1
	  else
	    priority = 0
    end
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    @todo_item.update_attribute(:priority, priority)
		redirect_to @todo_list
  end

  def edit
  end

  def update
    # @todo_item.update_attribute(:completed_at, Time.now)
    # deadline = @todo_item.deadline
    if @todo_item.update(todo_item_params)
      # @todo_item = @todo_list.todo_items.create(todo_item_params)
      # @todo_item_change = @todo_item.find(deadline: deadline)
      # @todo_item_change.save
      redirect_to @todo_list
      # format.html { redirect_to @todo_item, notice: 'Task was successfully updated.' }
      # format.json { render :show, status: :ok, location: @todo_item }
    else
      flash[:error] = "Todo List item coul not be edited."
      render 'edit'
    end
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item coul not be deleted."
    end
    redirect_to @todo_list
    # @t = @todo_list.todo_items.find_by(id: params[:id])
	  # @t.destroy
    #
	  # @todo_lists = current_user.todo_lists.order(:id)
	  #   respond_to do |format|
    #     format.html {redirect_to todolists_path}
    #     format.js {render action: 'script.js.erb'}
    #   end
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list #, notice: "Todo item complited"
  end

  def uncomplete
    @todo_item.update_attribute(:completed_at, nil)
    redirect_to @todo_list #, notice: "Todo item uncomplited"
  end

  def priority_up
    @todo_list_cur = current_user.todo_lists.find(@todo_item.todo_list_id)
    if @todo_item.priority != @todo_list_cur.todo_items.minimum(:priority)
  	  @todo_item_to_change=@todo_list_cur.todo_items.find_by(priority: (@todo_item.priority-1))
  	  @todo_item_to_change.priority += 1
  	  @todo_item_to_change.save
  	  @todo_item.priority -= 1
      @todo_item.save
      redirect_to @todo_list
      # @todo_lists = current_user.todo_lists.order(:id)
	    # respond_to do |format|
      #   format.html {redirect_to todolists_path}
      #   format.js {render action: 'script.js.erb'}
      # end
    end
  end

  def priority_down
    @todo_list_cur=current_user.todo_lists.find(@todo_item.todo_list_id)
    if @todo_item.priority != @todo_list_cur.todo_items.maximum(:priority)
  	  @todo_item_to_change=@todo_list_cur.todo_items.find_by(priority: (@todo_item.priority+1))
  	  @todo_item_to_change.priority -= 1
  	  @todo_item_to_change.save
  	  @todo_item.priority += 1
      @todo_item.save
      redirect_to @todo_list
    end
  end

  private
    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

  	def set_todo_item
  		@todo_item = @todo_list.todo_items.find(params[:id])
  	end

    def todo_item_params
  		params[:todo_item].permit(:content, :deadline, :completed_at)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Task" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
  <% if todo_item.completed? %>
    <div class="block-item" >
    <div class="complete">
      <%= link_to uncomplete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, data: { confirm: "Are you sure? Uncompleted" } do %>
        <i style="opacity: 0.4;" class="fa fa-minus"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to priority_up_todo_list_todo_item_path(@todo_list, todo_item.id, todo_item.priority), method: :post do %>
        <i style="opacity: 0.4;" class="fa fa-chevron-up"></i>
      <% end %>
      <%= link_to priority_down_todo_list_todo_item_path(@todo_list, todo_item.id, todo_item.priority), method: :post do %>
        <i style="opacity: 0.4;" class="fa fa-chevron-down"></i>
      <% end %>&nbsp
      <%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item.id, todo_item.deadline) do %>
        <i style="opacity: 0.4;" class="fa fa-pencil-alt"></i>
      <% end %>&nbsp
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i style="opacity: 0.4;" class="fa fa-trash"></i>
      <% end %>
    </div>
    </div>
  <% else %>
    <div class="block-item" >
      <div class="complete">
        <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
          <i class="fa fa-check"></i>
        <% end %>
      </div>
      <div class="todo_item" >
        <p><%= todo_item.content %></p>
      </div>
      <div class="trash">
        <%= link_to priority_up_todo_list_todo_item_path(@todo_list, todo_item.id, todo_item.priority), method: :post do %>
          <i class="fa fa-chevron-up"></i>
        <% end %>
        <%= link_to priority_down_todo_list_todo_item_path(@todo_list, todo_item.id, todo_item.priority), method: :post do %>
          <i class="fa fa-chevron-down"></i>
        <% end %>&nbsp
        <%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item, todo_item.deadline) do %>
          <i class="fa fa-pencil-alt"></i>
        <% end %>&nbsp
        <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<!-- <script>
  $(document).ready(function(){
    $("i").click( function(){
      $(this).parent().find('#form').toggle();
      $(this).parent().find('#edit-todo_list-form').toggle();
      });

    $("tr").hover( function(){
      $(this).find("#icons").toggle();
      });
    $(".panel-heading").hover( function(){
      $(this).find("#head_icons").toggle();
      });
  });
</script> -->

app/views/todo_items/edit.html.erb
<h1>Edit Task</h1>
<%= form_for([@todo_list, @todo_item ]) do |f| %>
  <%= f.text_field :content, lable: "Change task" %>
  <%= f.date_field :deadline, lable: "DeadLine" %>
  
  <%= f.button :submit %>
<% end %>