config/routes.rb
Rails.application.routes.draw do
  root                   'static_pages#home'

  get     'help'      => 'static_pages#help'
  get     'about'     => 'static_pages#about'
  get     'contact'   => 'static_pages#contact'

  get     'signup'    => 'users#new'

  get     'login'     => 'sessions#new'
  post    'login'     => 'sessions#create'
  delete  'logout'    => 'sessions#destroy'

  get     'todolists' => 'todo_lists#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
        patch :uncomplete
        post 'priority_up'
        post 'priority_down'
      end
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items, dependent: :destroy

  validates :title, :user_id,
            presence: true,
            length: {maximum: 140}
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list,  only: [:show, :edit, :update, :destroy]

  def index
    # @todo_lists = TodoList.all
    @todo_item = TodoList.new
    @todo_lists = current_user.todo_lists.order(:id)
  end

  def show
  end

  def new
    @todo_list = TodoList.new
  end

  def edit
  end

  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def have_access(todo_list)
      return true if todo_list && (todo_list.user_id == current_user.id)
      false
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title, :description, :user_id)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |form| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :todo_list_title %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :todo_list_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>

<div class="links" >
  <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
    <p class="todo_list_sub_title"><%= todo_list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "New Todo List", new_todo_list_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>
<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>

<div class="links">
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
  <h2 class="todo_list_title"><%= @todo_list.title %></h2>
  <p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">

  <%= render @todo_list.todo_items.order(:priority) %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>

</div>
<div class="links">
  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
  <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { comfirm: "Are you sure?" } %> |
  <%= link_to 'Back', todo_lists_path %>
</div>